import type { CarDto } from '../../src/types/type';

export const carsMock: CarDto[] = [
  { id: 1, name: 'Apex', color: '#6c779f' },
  { id: 2, name: 'Comet', color: '#4d9de0' },
  { id: 3, name: 'Mercedes', color: '#6c779f' },
  { id: 4, name: 'Viper', color: '#f25f5c' },
  { id: 5, name: 'Nebula', color: '#70c1b3' },
  { id: 6, name: 'Phantom', color: '#b388eb' },
  { id: 7, name: 'Rocket', color: '#ffd166' },
  { id: 8, name: 'Orion', color: '#06d6a0' },
  { id: 9, name: 'Nova', color: '#118ab2' },
  { id: 10, name: 'Blaze', color: '#ef476f' },
  { id: 11, name: 'Titan', color: '#8d99ae' },
  { id: 12, name: 'Quasar', color: '#a8dadc' },
  { id: 13, name: 'Shadow', color: '#5e60ce' },
  { id: 14, name: 'Pulse', color: '#9b5de5' },
  { id: 15, name: 'Storm', color: '#00bbf9' },
  { id: 16, name: 'Drift', color: '#00f5d4' },
  { id: 17, name: 'Sparrow', color: '#f15bb5' },
  { id: 18, name: 'Falcon', color: '#fee440' },
  { id: 19, name: 'Cobra', color: '#fb5607' },
  { id: 20, name: 'Aurora', color: '#3a86ff' },
  { id: 21, name: 'Aurora2', color: '#3a86ff' },
];
